# @host = http://localhost:8787/api/v1/phones
@host = https://ast_resp_ef_cfworkers.rafliyulistiawan.workers.dev/api/v1/phones

### GET ALL
GET {{host}}

### GET BY ID
GET {{host}}/12

### POST
POST {{host}}
Content-Type: application/json

{
  "model": "Model HP",
  "brand": "Merk HP",
  "ram": 24,
  "storage": 512,
  "price": 1199.56
}

### EDIT USER
PUT {{host}}/12
Content-Type: application/json

{
  "model": "Model HP sdasd",
  "brand": "Merk HP 2",
  "ram": 8,
  "storage": 256,
  "price": 1219.89
}

### DELETE USER
DELETE {{host}}/14